apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: wg-operator
  labels:
    app: wg-operator
    heritage: Tiller
  namespace: wg-operator
spec:
  selector:
    matchLabels:
      app: wg-operator
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wg-operator
    spec:
      serviceAccountName: wg-operator
      securityContext:
        runAsNonRoot: false
      hostNetwork: true
      containers:
        - name: wg-operator
          image: registry.gitlab.com/neven-miculinic/wg-operator:master-amd64
          imagePullPolicy: Always
          args:
            - --mode=server
            - --wg-interface=wg0
            - --node-name=$(HOSTNAME)
            - --wg-private-key-file=/etc/wireguard/wg0.key
          securityContext:
            capabilities:
              add:
              - "NET_ADMIN"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "wg-operator"
          volumeMounts:
          - name: private-key
            mountPath: /etc/wireguard/wg0.key
            readOnly: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux
      volumes:
        - name: private-key
          hostPath:
            path: /etc/wireguard/wg0.key
        - name: wg-config
          hostPath:
            path: /etc/wireguard/wg0.conf
